Models/ErrorViewModel.cs
namespace ITI_DOO.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/DownloadController.cs
using Microsoft.AspNetCore.Mvc;

namespace ITI_DOO.Controllers
{
    public class DownloadController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using ITI_DOO.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ITI_DOO.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/KontaktController.cs
using Microsoft.AspNetCore.Mvc;

namespace ITI_DOO.Controllers
{
    public class KontaktController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ReferenceController.cs
using Microsoft.AspNetCore.Mvc;

namespace ITI_DOO.Controllers
{
    public class ReferenceController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/SoftverController.cs
using Microsoft.AspNetCore.Mvc;

namespace ITI_DOO.Controllers
{
    public class SoftverController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/VestiController.cs
using Microsoft.AspNetCore.Mvc;

namespace ITI_DOO.Controllers
{
    public class VestiController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Download/Index.cshtml
@{
    ViewData["Title"] = "Download";
}

<!-- ======= Download Section ======= -->
    <section id="faq" class="faq section-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Preuzmi dokumente</h2>
        </div>

        <div class="faq-list">
          <ul>
            <li data-aos="fade-up" data-aos-delay="100">
              <i class="bi bi-download icon-help"></i> <a data-bs-toggle="collapse" class="collapse" data-bs-target="#faq-list-1">CheckIĆ - android aplikacija za prijavljivanje komunalnih problema na teritoriji Republike Srbije <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
              <div id="faq-list-1" class="collapse show" data-bs-parent=".faq-list">
                <p>
                    Preuzmi
                </p>
              </div>
            </li>

            <li data-aos="fade-up" data-aos-delay="200">
              <i class="bi bi-download icon-help"></i> <a data-bs-toggle="collapse" data-bs-target="#faq-list-2" class="collapsed">Opis i uputstvo aplikacije CheckIĆ - .doc format <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
              <div id="faq-list-2" class="collapse" data-bs-parent=".faq-list">
                <p>
                  Preuzmi
                </p>
              </div>
            </li>

            <li data-aos="fade-up" data-aos-delay="300">
              <i class="bi bi-download icon-help"></i> <a data-bs-toggle="collapse" data-bs-target="#faq-list-3" class="collapsed">Opis i uputstvo aplikacije CheckIĆ - .pdf format <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
              <div id="faq-list-3" class="collapse" data-bs-parent=".faq-list">
                <p>
                  Preuzmi
                </p>
              </div>
            </li>

            <li data-aos="fade-up" data-aos-delay="400">
              <i class="bi bi-download icon-help"></i> <a data-bs-toggle="collapse" data-bs-target="#faq-list-4" class="collapsed">Opis i uputstvo aplikacije CheckIĆ - .html format <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
              <div id="faq-list-4" class="collapse" data-bs-parent=".faq-list">
                <p>
                  Preuzmi
                </p>
              </div>
            </li>

            <li data-aos="fade-up" data-aos-delay="500">
              <i class="bi bi-download icon-help"></i> <a data-bs-toggle="collapse" data-bs-target="#faq-list-5" class="collapsed">Prezentacija aplikacije CheckIĆ - održana povodom konkursa Digitalne Agende <i class="bx bx-chevron-down icon-show"></i><i class="bx bx-chevron-up icon-close"></i></a>
              <div id="faq-list-5" class="collapse" data-bs-parent=".faq-list">
                <p>
                  Preuzmi
                </p>
              </div>
            </li>

          </ul>
        </div>

      </div>
    </section><!-- End Download Section -->

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "- O nama";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- ======= About Us Section ======= -->
    <section id="about" class="about">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Ko smo mi?</h2>
        </div>

        <div class="row content">
          <div class="col-lg-12">
            <p>
              Inđija, kao jedna od najrazvijenijih opština u Srbiji, veliki deo svog napretka duguje upravo ulaganju u informacione tehnologije. Razvoj inovativnih softvera poput Sistema48 ili Elektronskih sednica unapredio je rad lokalne uprave kroz ubrzavanje raznih procedura i velike uštede opštinskog budžeta.
            </p>
            <p>Kako se tokom vremena obim posla IT odeljenja širio, donesena je odluka o osnivanju Agencije za IT, GIS i komunikacije opštine Inđija.</p>
            <p>Agencija od 2009. godine nastupa samostalno na tržištu, nudeći preko dvadeset samostalno osmišljenih i razvijenih IT rešenja.</p>
          </div>
        </div>

      </div>
    </section>

    <section class="about section-bg">
      <div class="container" data-aos="fade-up">

        <div class="row content">
          <div class="col-lg-8" data-aos="fade-right" data-aos-delay="100">
            <p>
              Na sednici opštinskog veća 18.decembra 2008. godine usvojen je početni dokument za osnivanje agencije.
            </p>
            <p style="font-style:italic;">Radi pružanja podrške naporima Opštine u obavljanju redovnih delatnosti u domenu informatičkih delatnosti, delatnosti komunikacija i publikovanja dokumenata iz oblasti prostornog uređenja opštine Inđija, Opština Inđija pristupa osnivanju Društva sa ograničenom odgovornošću „Agencije za IT, GIS i komunikacije Opštine Inđija“, Inđija (ITI d.o.o.), u svojstvu jednog od osnivača.</p>        
          </div>
          <div class="col-lg-4 align-items-stretch order-1 order-lg-2 img" data-aos="fade-left" data-aos-delay="300" style="background-repeat: no-repeat;text-align:center">
              <img src="~/images/potpisivanje.jpg" />
          </div>
        </div>

      </div>
    </section>

    <section class="about">
      <div class="container" data-aos="fade-up">
        
        <div class="row content">
            <p style="font-weight:600;">Agencija za IT, GIS i komunikacije opštine Inđija je osnovana krajem jula 2009. godine a počela je da funkcioniše 01.septembra 2009.</p><br /><br /><br />
        </div>
        <div class="row content">
          <div class="col-lg-2 align-items-stretch img" data-aos="zoom-in" data-aos-delay="150">
            <img src="~/images/laptop.jpg" />       
          </div>
          <div class="col-lg-10" data-aos="fade-left" data-aos-delay="100" style="background-repeat: no-repeat;">
              <p><b>Osnovni podaci:</b><br />
                  Agenciji za IT, GIS i komunikacije Opštine Inđija ITI d.o.o
              </p>
              <p><b>Matični broj:</b> 20550988</p>
              <p><b>PIB:</b> 106185490</p>
              <p><b>Pretežna delatnost:</b> 6201 – Računarsko programiranje</p>
              <p><b>Kapital novčani:</b> 1.000,00 €</p>
              <p><b>Podaci o osnivačima:</b></p>
                  <ul>
                      <li><i class="ri-check-double-line"></i>Opština Inđija, Inđija, Cara Dušana 1</li>
                      <li><i class="ri-check-double-line"></i>Društvo za konsalting, inženjering i zastupanje u oblasti geografskih informacionih sistema GISDATA doo Beograd, Bulevar Mihajla Pupina 165e</li>
                  </ul>
              <p><b>Skupština društva :</b><br />
                  Članovi društva s ograničenom odgovornošću čine skupštinu Predsednik skupštine društva Nemanja Milojević</p>
          </div>
        </div>

      </div>
    </section>

Views/Kontakt/Index.cshtml
@{
    ViewData["Title"] = "Kontakt";
}

<!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h2>Kontakt</h2>
          <p>Agencija za IT, GIS i komunikacije opštine Inđija</p>
        </div>

        <div class="row">

          <div class="col-lg-4 d-flex align-items-stretch">
            <div class="info">
              <div class="address">
                <i class="bi bi-geo-alt"></i>
                <h4>Adresa:</h4>
                <p>Cara Dušana 1, Inđija</p>
              </div>

              <div class="email">
                <i class="bi bi-envelope"></i>
                <h4>Mail:</h4>
                <p>iti@indjija.net</p>
              </div>

              <div class="phone">
                <i class="bi bi-phone"></i>
                <h4>Telefon:</h4>
                <p>+381 (0) 22 560 002</p>
              </div>

              <div class="phone">
                <i class="bi bi-telephone"></i>
                <h4>Fax:</h4>
                <p>+381 (0) 22 560 002</p>
              </div>

              <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2818.9557427391155!2d20.076159376734555!3d45.04611996123597!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x475af8b938534501%3A0x46a80eba4c535b06!2sCara%20Du%C5%A1ana%201%2C%20In%C4%91ija%2022320!5e0!3m2!1ssr!2srs!4v1697377669272!5m2!1ssr!2srs" frameborder="0" style="border:0; width: 100%; height: 290px;" allowfullscreen></iframe>
            </div>

          </div>

          <div class="col-lg-5 mt-5 mt-lg-0 d-flex align-items-stretch">
            <form action="forms/contact.php" method="post" role="form" class="php-email-form">
              <div class="row">
                <div class="form-group col-md-6">
                  <label for="name">Ime i prezime</label>
                  <input type="text" name="name" class="form-control" id="name" required>
                </div>
                <div class="form-group col-md-6">
                  <label for="name">E-mail</label>
                  <input type="email" class="form-control" name="email" id="email" required>
                </div>
              </div>
              <div class="form-group">
                <label for="name">Subject</label>
                <input type="text" class="form-control" name="subject" id="subject" required>
              </div>
              <div class="form-group">
                <label for="name">Poruka</label>
                <textarea class="form-control" name="message" rows="10" required></textarea>
              </div>
              <div class="my-3">
                <div class="loading">Učitavanje</div>
                <div class="error-message"></div>
                <div class="sent-message">Vaša poruka je poslata. Hvala Vam!</div>
              </div>
              <div class="text-center"><button type="submit">Pošalji</button></div>
            </form>
          </div>

          <div class="col-lg-3 mt-5 mt-lg-0 d-flex align-items-stretch">
            <div id="info" class="info">
              <div class="address">
                <h4>PIB</h4>
                <p>106185490</p>
              </div>

              <div class="email">
                <h4>Matični broj</h4>
                <p>20550988</p>
              </div>

              <div class="phone">
                <h4>Šifra delatnosti</h4>
                <p>6201</p>
              </div>

              <div class="phone">
                <h4>Dodeljeni RZZO registracioni broj</h4>
                <p>4000079030</p>
              </div>

              <div class="phone">
                <h4>Pun naziv firme</h4>
                <p>Agencija za IT, GIS i komunikacije opštine Inđija</p>
              </div>

              <div class="phone">
                <h4>Skraćeni naziv firme</h4>
                <p>ITI doo Inđija</p>
              </div>

              <div class="phone">
                <h4>Direktor firme</h4>
                <p>Dejan Kurtović</p>
              </div>

            </div>

          </div>

        </div>

      </div>
    </section><!-- End Contact Section -->

Views/Reference/Index.cshtml
@{
    ViewData["Title"] = "Reference";
}

<!-- ======= Services Section ======= -->
<section id="services" class="services section-bg">
    <div class="container" data-aos="fade-up">
        <div class="row">
            <div class="col-xl-3 col-md-4 align-items-stretch" data-aos="zoom-in" data-aos-delay="100">
                <div class="row">
                    <div class="flex-row align-items-stretch mt-1 mt-md-1" data-aos="zoom-in" data-aos-delay="200">
                        <div class="icon-soft">
                            <h4><a href="">Opština Inđija</a></h4>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="flex-row align-items-stretch mt-1 mt-md-1" data-aos="zoom-in" data-aos-delay="200">
                        <div class="icon-soft">
                            <h4><a href="">Direkcija za izgradnju opštine Inđija</a></h4>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="flex-row align-items-stretch mt-1 mt-md-1" data-aos="zoom-in" data-aos-delay="200">
                        <div class="icon-soft">
                            <h4><a href="">Opština Apatin</a></h4>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="flex-row align-items-stretch mt-1 mt-md-1" data-aos="zoom-in" data-aos-delay="200">
                        <div class="icon-soft">
                            <h4><a href="">Grad Skoplje</a></h4>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="flex-row align-items-stretch mt-1 mt-md-1" data-aos="zoom-in" data-aos-delay="200">
                        <div class="icon-soft">
                            <h4><a href="">Opština Temerin</a></h4>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="flex-row align-items-stretch mt-1 mt-md-1" data-aos="zoom-in" data-aos-delay="200">
                        <div class="icon-soft">
                            <h4><a href="">Opština Ruma</a></h4>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="flex-row align-items-stretch mt-1 mt-md-1" data-aos="zoom-in" data-aos-delay="200">
                        <div class="icon-soft">
                            <h4><a href="">Opština Žabalj</a></h4>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="flex-row align-items-stretch mt-1 mt-md-1" data-aos="zoom-in" data-aos-delay="200">
                        <div class="icon-soft">
                            <h4><a href="">Kulturni centar Inđija</a></h4>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="flex-row align-items-stretch mt-1 mt-md-1" data-aos="zoom-in" data-aos-delay="200">
                        <div class="icon-soft">
                            <h4><a href="">Biblioteka Dr. Đorđe Natošević</a></h4>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="flex-row align-items-stretch mt-1 mt-md-1" data-aos="zoom-in" data-aos-delay="200">
                        <div class="icon-soft">
                            <h4><a href="">Fudbalski klub Inđija</a></h4>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="flex-row align-items-stretch mt-1 mt-md-1" data-aos="zoom-in" data-aos-delay="200">
                        <div class="icon-soft">
                            <h4><a href="">Osnovna škola Petar Kočić</a></h4>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="flex-row align-items-stretch mt-1 mt-md-1" data-aos="zoom-in" data-aos-delay="200">
                        <div class="icon-soft">
                            <h4><a href="">Predškolska ustanova Boško Buha</a></h4>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="flex-row align-items-stretch mt-1 mt-md-1" data-aos="zoom-in" data-aos-delay="200">
                        <div class="icon-soft">
                            <h4><a href="">Savez sportova Inđija</a></h4>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="flex-row align-items-stretch mt-1 mt-md-1" data-aos="zoom-in" data-aos-delay="200">
                        <div class="icon-soft">
                            <h4><a href="">Agencija za ruralni razvoj opštine Inđija</a></h4>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="flex-row align-items-stretch mt-1 mt-md-1" data-aos="zoom-in" data-aos-delay="200">
                        <div class="icon-soft">
                            <h4><a href="">Vlada autonomne pokrajine Vojvodine</a></h4>
                        </div>
                    </div>
                </div>
            </div>

            <div class="container-fluid col-xl-9 col-md-8 mt-sm-3 mt-lg-1 mt-md-1 align-items-stretch icon-news" data-aos="zoom-in" data-aos-delay="100" style="height:inherit;">
                <div class="row">
                    <div class="flex-row align-items-stretch mt-1 mt-md-1">
                        <div class="align-items-stretch mt-1 mt-md-1 img" data-aos="zoom-in" data-aos-delay="700">                      
                            <h4><img id="refimg" src="~/images/reference/indjija.png" /> Opština Inđija</h4>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="flex-row align-items-stretch mt-1 mt-md-1">
                        <div class="align-items-stretch mt-1 mt-md-1 img" data-aos="zoom-in" data-aos-delay="700">                      
                            <p class="mt-0 mb-1">Sistem48</p>
                            <p class="mt-0 mb-1">Elektronske sednice</p>
                            <p class="mt-0 mb-1">Obračun lokalnih prihoda</p>
                            <p class="mt-0 mb-1">Adresni registar</p>
                            <p class="mt-0 mb-1">Pisarnica</p>
                            <p class="mt-0 mb-1">Matične knjige</p>
                            <p class="mt-0 mb-1">Birački spisak</p>
                            <p class="mt-0 mb-1">SMS servis</p>
                            <p class="mt-0 mb-1">Kadrovska evidencija</p>
                            <p class="mt-0 mb-1">Registar lica</p>
                            <p class="mt-0 mb-1">Administrativni modul</p>
                            <p class="mt-0 mb-1">Infomacioni sistem</p>
                            <p class="mt-0 mb-1">Osnovna sredstva</p>
                            <p class="mt-0 mb-1">Imovina</p>
                            <p class="mt-0 mb-1">GIS <a href="">pogledaj</a></p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section><!-- End Services Section -->

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ITI DOO - Inđija @ViewData["Title"]</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/images/favicon.png" rel="icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i%7CJost:300,300i,400,400i,500,500i,600,600i,700,700i%7CPoppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/lib/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/lib/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/lib/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/lib/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/lib/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/lib/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/lib/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/css/style.css" rel="stylesheet" asp-append-version="true"> 
</head>
<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top">
        <div class="container d-flex align-items-center">

            <h1 class="logo me-auto"><a asp-controller="Home" asp-action="Index"><img src="~/images/iti_logo.png" alt=""></a></h1>

            <nav id="navbar" class="navbar">
                <ul>
                     <li><a class="nav-link" asp-controller="Home" asp-action="Index">O nama</a></li>
                     <li><a class="nav-link" asp-controller="Vesti" asp-action="Index">Vesti</a></li>
                     <li><a class="nav-link" asp-controller="Softver" asp-action="Index">Softver</a></li>
                     <li><a class="nav-link" asp-controller="Reference" asp-action="Index">Reference</a></li>
                     <li><a class="nav-link" asp-controller="Kontakt" asp-action="Index">Kontakt</a></li>
                     <li><a class="nav-link" asp-controller="Download" asp-action="Index">Download</a></li>
                 </ul>
                 <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->
         </div>
    </header>

    <!-- ======= Hero Section ======= -->
    <section id="hero" class="d-flex align-items-center">

    <div class="container">
        <div class="row">
            <div class="col-lg-6 d-flex flex-column justify-content-center pt-4 pt-lg-0 order-2 order-lg-1" data-aos="fade-up" data-aos-delay="200">
                <h1>Mi imamo ideje</h1>
                <h2>efikasna, sveža, praktična IT rešenja</h2>
                <h3>"Inđija je postala jedna od najpopularnijih destinacija za ulaganje, ne samo u Srbiji,
                    već i u regionu Jugoistočne Evrope, prvenstveno zbog brze i uslužne administracije,
                    dobre infrastrukture i primene najmodernijih informacionih tehnologija"
                    <br />
                    (Financial times, fDI Magazine)
                    <br /><br />
                    Spremni smo da podelimo sa Vama naše dugogodišnje iskustvo na polju informacionih tehnologija.
                </h3>
            </div>
            <div class="col-lg-6 order-1 order-lg-2 hero-img" data-aos="zoom-in" data-aos-delay="200">
                <img src="~/images/hero.png" class="img-fluid animated" alt="">
            </div>
        </div>
    </div>

   </section>

     <div>
         <main role="main" class="pb-3">
             @RenderBody()
         </main>
     </div>

    <!-- ======= Footer ======= -->
   <footer id="footer">
       <div class="container d-flex footer-bottom clearfix justify-content-center">
           <div class="copyright">
                &copy; 2011 iti.indjija.rs, all rights reserved.
           </div>
       </div>
   </footer>

     <div id="preloader"></div>
     <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/lib/vendor/aos/aos.js" asp-append-version="true"></script>
    <script src="~/lib/vendor/bootstrap/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/lib/vendor/glightbox/js/glightbox.min.js" asp-append-version="true"></script>
    <script src="~/lib/vendor/isotope-layout/isotope.pkgd.min.js" asp-append-version="true"></script>
    <script src="~/lib/vendor/swiper/swiper-bundle.min.js" asp-append-version="true"></script>
    <script src="~/lib/vendor/waypoints/noframework.waypoints.js" asp-append-version="true"></script>
    <script src="~/lib/vendor/php-email-form/validate.js" asp-append-version="true"></script> 
    <script src="~/js/main.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Vesti/Index.cshtml
@{
    ViewData["Title"] = "Vesti";
}

<!-- ======= Services Section ======= -->
<section id="services" class="services section-bg">
    <div class="container text-center" data-aos="fade-up">
        <div class="row">
            <div class="col-xl-4 col-md-6 align-items-stretch" data-aos="zoom-in" data-aos-delay="100">
                <div class="row">
                    <div class="d-flex align-items-stretch mt-2 mt-md-2" data-aos="zoom-in" data-aos-delay="100">
                        <div class="icon-box">
                            <h4><a href="">Lorem Ipsum</a></h4>
                            <p>Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi</p>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="d-flex align-items-stretch mt-2 mt-md-2" data-aos="zoom-in" data-aos-delay="100">
                        <div class="icon-box">
                            <h4><a href="">Sed ut perspici</a></h4>
                            <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore</p>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="d-flex align-items-stretch mt-2 mt-md-2" data-aos="zoom-in" data-aos-delay="100">
                        <div class="icon-box">                            
                            <h4><a href="">Magni Dolores</a></h4>
                            <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia</p>
                        </div>
                    </div>
                </div>
     
            </div>

            <div class="col-xl-8 col-md-6 align-items-stretch" data-aos="zoom-in" data-aos-delay="100">
                <div class="row" style="height:100%;">
                    <div class="align-items-stretch mt-2 mt-md-2" data-aos="zoom-in" data-aos-delay="700">
                        <div class="icon-news">
                            <h4>Lorem Ipsum</h4>
                            <p>Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi</p>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section><!-- End Services Section -->